import React, { useState } from 'react';
import { HelpCircle, ChevronDown } from 'lucide-react';

export default function UKStatsAndFAQ() {
  const [activeFaq, setActiveFaq] = useState(0);

  const faqs = [
    {
      q: "What is the UK Graduate Route (PSW) work permit?",
      a: "The Graduate Route allows international students who successfully complete an eligible degree (Bachelor or Master's) to live and work in the UK for up to 2 years. Doctoral (PhD) graduates receive a 3-year permit."
    },
    {
      q: "Are students allowed to work part-time in the UK?",
      a: "Yes. Students enrolled at higher education institutions on full-time student visas can work up to 20 hours per week off-campus during term times and full-time during official university holidays."
    },
    {
      q: "Can I bring my family dependents under a UK Student Visa?",
      a: "Following the UKVI updates of January 2024, only postgraduate research courses (Research Masters or PhDs) or students under select government-sponsored fellowship awards can sponsor dependents."
    },
    {
      q: "What is the CAS and how do I receive it?",
      a: "A CAS (Confirmation of Acceptance for Studies) is an online document generated by your university. To secure it, you complete any conditional entry guidelines, pass a pre-CAS interview, and deposit a minimum fee."
    },
    {
      q: "How long does standard UK Student Visa processing take?",
      a: "Most standard student visa applications are approved within 15 working days. Priority services take 5 working days, while Super Priority ensures a decision in 24 hours."
    }
  ];

  return (
    <div className="bg-white rounded-3xl p-6 md:p-10 border border-gray-100 shadow-sm space-y-6">
      <div className="space-y-1">
        <span className="text-xs font-bold text-[#f15b24] font-mono uppercase tracking-wider block">
          Information Center
        </span>
        <h3 className="text-xl md:text-2xl font-extrabold text-[#2c3164] font-serif tracking-tight">
          Frequently Asked Questions (FAQs)
        </h3>
        <p className="text-gray-400 text-xs text-left">
          Quick, official advice regarding your UK higher education applications.
        </p>
      </div>

      <div className="space-y-3 max-w-4xl text-left">
        {faqs.map((faq, i) => (
          <div
            key={i}
            className="border border-slate-100 rounded-xl overflow-hidden transition-all duration-300"
          >
            <button
              id={`uk-faq-btn-${i}`}
              onClick={() => setActiveFaq(activeFaq === i ? -1 : i)}
              className="w-full text-left px-5 py-4 bg-slate-50 hover:bg-slate-100/70 transition-colors flex justify-between items-center gap-4 cursor-pointer"
            >
              <span className="text-xs md:text-sm font-extrabold text-[#2c3164] flex items-center gap-2.5">
                <HelpCircle size={15} className="text-[#f15b24] shrink-0" />
                <span>{faq.q}</span>
              </span>
              <ChevronDown
                size={16}
                className={`text-[#2c3164]/60 transition-transform duration-300 ${activeFaq === i ? 'rotate-180' : ''}`}
              />
            </button>

            <div
              className={`bg-white transition-all duration-300 overflow-hidden ${
                activeFaq === i ? 'max-h-40 px-5 py-4 border-t border-slate-100' : 'max-h-0'
              }`}
            >
              <p className="text-xs text-gray-500 leading-relaxed font-sans">{faq.a}</p>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
